/**
 * Background removal — deterministic BFS engine tests.
 * Tests the core algorithm functions and the engine execute/validate cycle
 * using real fixture images generated by generate-alpha-fixtures.mjs.
 */

import { describe, it, expect, beforeAll } from "vitest";
import fs from "fs";
import path from "path";
import os from "os";
import {
  buildAlphaMaskBFS,
  erodeAlphaMask,
  applyMaskToPixels,
  BackgroundRemovalEngine,
} from "../../src/lib/engines/background/background-removal-engine";

const FIXTURES = path.resolve(import.meta.dirname ?? __dirname, "../fixtures");
const tmpDir = fs.mkdtempSync(path.join(os.tmpdir(), "anclora-bfs-test-"));

// Point the engine's path safety check to our tmpDir
process.env.ANCLORA_FILESTUDIO_TEMP_DIR = tmpDir;

// Copy fixture to tmpDir so it's under the allowed temp root
function fixtureInTmp(name: string): string {
  const src = path.join(FIXTURES, name);
  const dst = path.join(tmpDir, name);
  if (fs.existsSync(src)) fs.copyFileSync(src, dst);
  return dst;
}

function fixturePath(name: string): string {
  return fixtureInTmp(name);
}

// ── BFS algorithm unit tests ──────────────────────────────────────────────────

describe("buildAlphaMaskBFS — unit", () => {
  it("removes all pixels in a solid white 4×4 image", () => {
    // 4×4 fully white RGBA image (all pixels near-white)
    const w = 4, h = 4;
    const pixels = new Uint8Array(w * h * 4).fill(255);
    const mask = buildAlphaMaskBFS(pixels, w, h, { threshold: 30 });
    expect(Array.from(mask).every((v) => v === 0)).toBe(true);
  });

  it("keeps interior teal pixels when surrounded by white", () => {
    // 6×6: white border + teal 2×2 center at (2,2)-(3,3)
    const w = 6, h = 6;
    const pixels = new Uint8Array(w * h * 4);
    for (let y = 0; y < h; y++) {
      for (let x = 0; x < w; x++) {
        const i = (y * w + x) * 4;
        const isCenter = x >= 2 && x <= 3 && y >= 2 && y <= 3;
        pixels[i] = isCenter ? 20 : 255;
        pixels[i + 1] = isCenter ? 184 : 255;
        pixels[i + 2] = isCenter ? 166 : 255;
        pixels[i + 3] = 255;
      }
    }
    const mask = buildAlphaMaskBFS(pixels, w, h, { threshold: 30 });
    // All border pixels should be removed
    expect(mask[0]).toBe(0);  // top-left corner
    expect(mask[5]).toBe(0);  // top-right corner
    expect(mask[(h - 1) * w]).toBe(0); // bottom-left
    // Center pixels should be kept
    expect(mask[2 * w + 2]).toBe(255);
    expect(mask[3 * w + 3]).toBe(255);
  });

  it("respects black background hint", () => {
    const w = 4, h = 4;
    // All pixels are pure black (R=G=B=0) with alpha=255
    const pixels = new Uint8Array(w * h * 4); // starts all 0
    for (let i = 3; i < w * h * 4; i += 4) pixels[i] = 255; // set alpha channel only
    const mask = buildAlphaMaskBFS(pixels, w, h, { threshold: 30, backgroundHint: "black" });
    expect(Array.from(mask).every((v) => v === 0)).toBe(true);
  });

  it("handles checkerboard hint — removes both white and light gray", () => {
    const w = 4, h = 4;
    const pixels = new Uint8Array(w * h * 4);
    // Alternating white (255) and light gray (204)
    for (let y = 0; y < h; y++) {
      for (let x = 0; x < w; x++) {
        const i = (y * w + x) * 4;
        const val = ((x + y) % 2 === 0) ? 255 : 204;
        pixels[i] = val; pixels[i + 1] = val; pixels[i + 2] = val; pixels[i + 3] = 255;
      }
    }
    const mask = buildAlphaMaskBFS(pixels, w, h, { threshold: 30, backgroundHint: "checkerboard" });
    // All edge pixels of any color should be removed since it's all background
    expect(mask[0]).toBe(0);
    expect(mask[1]).toBe(0);
  });
});

describe("erodeAlphaMask — unit", () => {
  it("erodes interior keep-pixels adjacent to remove-pixels", () => {
    const w = 4, h = 4;
    const mask = new Uint8Array(w * h).fill(255); // all keep
    // Use interior pixel (1,1) = index 5 as the removed pixel
    mask[1 * w + 1] = 0;
    const eroded = erodeAlphaMask(mask, w, h);
    // Adjacent interior pixels should be eroded: (2,1) and (1,2)
    expect(eroded[1 * w + 2]).toBe(0);  // pixel (2, 1)
    expect(eroded[2 * w + 1]).toBe(0);  // pixel (1, 2)
    // Non-adjacent interior pixel (2,2) should remain 255
    expect(eroded[2 * w + 2]).toBe(255);
  });

  it("does not modify fully transparent mask", () => {
    const mask = new Uint8Array(16).fill(0);
    const result = erodeAlphaMask(mask, 4, 4);
    expect(Array.from(result).every((v) => v === 0)).toBe(true);
  });
});

describe("applyMaskToPixels — unit", () => {
  it("sets alpha to 0 for masked pixels", () => {
    const w = 2, h = 2;
    const pixels = new Uint8Array(w * h * 4).fill(255);
    const mask = new Uint8Array([0, 255, 255, 0]); // remove corners
    const result = applyMaskToPixels(pixels, mask, w, h);
    expect(result[3]).toBe(0);    // pixel 0 alpha removed
    expect(result[7]).toBe(255);  // pixel 1 alpha kept
    expect(result[11]).toBe(255); // pixel 2 alpha kept
    expect(result[15]).toBe(0);   // pixel 3 alpha removed
  });
});

// ── Full engine execution tests ───────────────────────────────────────────────

describe("BackgroundRemovalEngine — deterministic mode", () => {
  let engine: BackgroundRemovalEngine;

  beforeAll(() => {
    engine = new BackgroundRemovalEngine();
  });

  it("probe reports available (sharp installed)", async () => {
    const probe = await engine.probe();
    expect(probe.available).toBe(true);
    expect(probe.capabilities).toContain("deterministic");
  });

  it("removes white background from white-bg-logo.png", async () => {
    const inputPath = fixturePath("white-bg-logo.png");
    const outputPath = path.join(tmpDir, "white-bg-removed.png");

    if (!fs.existsSync(inputPath)) {
      console.warn("Fixture white-bg-logo.png not found — run generate-alpha-fixtures.mjs");
      return;
    }

    const result = await engine.execute({
      jobId: "test-1",
      operation: "remove-background",
      args: [],
      env: {},
      estimatedSizeBytes: null,
      inputPath,
      outputPath,
      outputFormat: "png",
      engineId: "background-removal" as import("../../src/lib/domain/engines").EngineId,
      options: { mode: "deterministic", backgroundHint: "white", threshold: 30 },
      timeoutMs: 30000,
    });

    expect(result.success).toBe(true);
    expect(fs.existsSync(outputPath)).toBe(true);

    const validation = await engine.validate(outputPath, {} as never);
    expect(validation.checks.find((c) => c.name === "has-alpha-channel")?.passed).toBe(true);
    expect(validation.checks.find((c) => c.name === "has-transparent-pixels")?.passed).toBe(true);
    expect(validation.valid).toBe(true);
  }, 30000);

  it("removes black background from black-bg-logo.png", async () => {
    const inputPath = fixturePath("black-bg-logo.png");
    const outputPath = path.join(tmpDir, "black-bg-removed.png");

    if (!fs.existsSync(inputPath)) return;

    const result = await engine.execute({
      jobId: "test-2",
      operation: "remove-background",
      args: [],
      env: {},
      estimatedSizeBytes: null,
      inputPath,
      outputPath,
      outputFormat: "png",
      engineId: "background-removal" as import("../../src/lib/domain/engines").EngineId,
      options: { mode: "deterministic", backgroundHint: "black", threshold: 30 },
      timeoutMs: 30000,
    });

    expect(result.success).toBe(true);
    const sharp = (await import("sharp")).default;
    const meta = await sharp(outputPath).metadata();
    expect(meta.hasAlpha).toBe(true);
  }, 30000);

  it("handles checkerboard pattern from checker-8.png", async () => {
    const inputPath = fixturePath("checker-8.png");
    const outputPath = path.join(tmpDir, "checker-removed.png");

    if (!fs.existsSync(inputPath)) return;

    const result = await engine.execute({
      jobId: "test-3",
      operation: "remove-background",
      args: [],
      env: {},
      estimatedSizeBytes: null,
      inputPath,
      outputPath,
      outputFormat: "png",
      engineId: "background-removal" as import("../../src/lib/domain/engines").EngineId,
      options: { mode: "deterministic", backgroundHint: "checkerboard", threshold: 60 },
      timeoutMs: 30000,
    });

    expect(result.success).toBe(true);
  }, 30000);

  it("preserves logo with holes — interior white is kept", async () => {
    const inputPath = fixturePath("logo-with-holes.png");
    const outputPath = path.join(tmpDir, "holes-removed.png");

    if (!fs.existsSync(inputPath)) return;

    const result = await engine.execute({
      jobId: "test-4",
      operation: "remove-background",
      args: [],
      env: {},
      estimatedSizeBytes: null,
      inputPath,
      outputPath,
      outputFormat: "png",
      engineId: "background-removal" as import("../../src/lib/domain/engines").EngineId,
      options: { mode: "deterministic", backgroundHint: "white", threshold: 30, haloReduction: false },
      timeoutMs: 30000,
    });

    // BFS from edges should not reach interior white hole because the teal frame blocks it
    expect(result.success).toBe(true);
    const sharp = (await import("sharp")).default;
    const meta = await sharp(outputPath).metadata();
    expect(meta.hasAlpha).toBe(true);
  }, 30000);

  it("does not fail on already-transparent image", async () => {
    const inputPath = fixturePath("already-transparent.png");
    const outputPath = path.join(tmpDir, "already-transparent-out.png");

    if (!fs.existsSync(inputPath)) return;

    const result = await engine.execute({
      jobId: "test-5",
      operation: "remove-background",
      args: [],
      env: {},
      estimatedSizeBytes: null,
      inputPath,
      outputPath,
      outputFormat: "png",
      engineId: "background-removal" as import("../../src/lib/domain/engines").EngineId,
      options: { mode: "deterministic" },
      timeoutMs: 30000,
    });

    expect(result.success).toBe(true);
  }, 30000);
});
